
import img12 from "../assets/img12.jpg"
import img13 from "../assets/img13.jpg"
import img14 from "../assets/img14.jpg"
import img15 from "../assets/img15.jpg"
import img16 from "../assets/img16.jpg"
import img17 from "../assets/img17.jpg"
import img18 from "../assets/img18.jpg"
import img19 from "../assets/img19.jpg"

export const COURSESDATA  = [
    {
        id: 1,
        courseid:"c1",
        image: img15,
        status: "Trending",
        modules: "9 Modules",
        duration: "7 Months",
        title: "Full Stack Development",
        coursename:"MEA(R)N Stack Web Development Expert",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 2,
        courseid:"c2",
        image: img12,
        status: "New",
        modules: "7 Modules",
        duration: "5 Months",
        title: "Robotics with AI",
        coursename:"Robotics with AI & IoT Training",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 3,
        courseid:"c3",
        image: img13,
        status:"Recommended",
        modules: "6 Modules",
        duration: "4 Months",
        title: "Software Testing",
        coursename:"Software Testing Training (AI Powered) - Manual & Automation",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 4,
        courseid:"c4",
        image: img14,
        status:"Most placed",
        modules: "9 Modules",
        duration: "6 Months",
        title: "Python Django - React",
        coursename:"Python Django - React - Full Stack Web Development Expert",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 5,
        courseid:"c5",
        image: img15,
        status:"Recommended",
        modules: "10 Modules",
        duration: "9 Months",
        title: "PYTHON DATA SCIENCE",
        coursename:"PYTHON DATA SCIENCE - ML - AI - & Power BI",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 6,
        courseid:"c6",
        image: img16,
        status:"Recommended",
        modules: "9 Modules",
        duration: "8 Months",
        title: "Java Spring boot",
        coursename:"Java Spring Full Stack Development",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 7,
        courseid:"c7",
        image: img17,
        status:"Recommended",
        modules: "9 Modules",
        duration: "7 Months",
        title: "Asp.net MVC",
        coursename:"Asp.net MVC with Angular - Full Stack",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 8,
        courseid:"c8",
        image: img18,
        status:"Most placed",
        modules: "9 Modules",
        duration: "8 Months",
        title: "Python Data Analytics",
        coursename:"Python Data Analytics with Power BI",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 9,
        courseid:"c9",
        image: img19,
        status:"Recommended",
        modules: "9 Modules",
        duration: "6 Months",
        title: "Flutter",
        coursename:"Best Flutter Training In Kochi (Cochin) & Calicut (Kozhikode)",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
]