
import img12 from "../assets/img12.jpg"
import img13 from "../assets/img13.jpg"
import img14 from "../assets/img14.jpg"
import img15 from "../assets/img15.jpg"
import img16 from "../assets/img16.jpg"
import img17 from "../assets/img17.jpg"
import img18 from "../assets/img18.jpg"
import img19 from "../assets/img19.jpg"

export const COURSESDATA  = [
    {
        id: 1,
        courseid:"c1",
        image: img15,
        status: "Trending",
        modules: "9 Modules",
        duration: "7 Months",
        title: "Full Stack Development",
        coursename:"MEA(R)N Stack Web Development Expert",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
    {
        id: 2,
        courseid:"c2",
        image: img12,
        status: "New",
        modules: "7 Modules",
        duration: "5 Months",
        title: "Robotics with AI",
        coursename:"Robotics with AI & IoT Training",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"12+",
        courseDescription: "AI-Driven Control Systems: Integrating AI, ML, IoT, and robotics Real-world applications: Autonomous robots for industries (e.g., delivery, healthcare) Final Project Work: Design and develop an AI-based autonomous robot, integrating IoT",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "CAD Design Tools & 3D Modelling",
            "Advanced 3D Design & 3D Printing",
            "Electronics Fundamentals & PCB Designing",
            "IoT Basics & Embedded Programming",
            "Introduction to Robotics",
            "Robot Operating System (ROS)",
        ],
    },
    {
        id: 3,
        courseid:"c3",
        image: img13,
        status:"Recommended",
        modules: "6 Modules",
        duration: "4 Months",
        title: "Software Testing",
        coursename:"Software Testing Training (AI Powered) - Manual & Automation",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"15",
        languagAndTools:"17+",
        courseDescription: "Software testing is an important function in many businesses. The job of a software tester can be very challenging but can be satisfying for people who are interested in problem-solving and risk management. The demand for software testers is on the rise and if you are searching for a way to start a career in the field of IT, then a software tester can be a good option.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "Manual Testing",
            "SQL",
            "JAVA",
            "SELENIUM IDE",
            "SELENIUM WEBDRIVER",
            "JIRA",
        ],
    },
    {
        id: 4,
        courseid:"c4",
        image: img14,
        status:"Most placed",
        modules: "9 Modules",
        duration: "6 Months",
        title: "Python Django - React",
        coursename:"Python Django - React - Full Stack Web Development Expert",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "Python is a hot programming language these days and for good reason. The community around machine learning, web development, data science, and artificial intelligence is growing exponentially and Python is a programming language that can open your doors to the world of programming. Among various server-side software languages, Python is considered easy to learn, read and write. In addition, the language is very much scalable.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "Core Python",
            "Advanced Python",
            "Django Framework",
            "Django Rest Framework",
            "React JS",
        ],
    },
    {
        id: 5,
        courseid:"c5",
        image: img15,
        status:"Recommended",
        modules: "10 Modules",
        duration: "9 Months",
        title: "PYTHON DATA SCIENCE",
        coursename:"PYTHON DATA SCIENCE - ML - AI - & Power BI",
        rating:"4.97",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"18",
        languagAndTools:"19+",
        courseDescription: "Machine learning is a data analysis method that is used to automate analytical model building. It is a subset of Artificial Intelligence (AI) and focuses on analyzing structures and patterns in data to allow reasoning, learning, and decision-making without human interactions. In simple terms, Machine learning will let the user feed large volumes of data to a computer algorithm.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "Python & Advanced Python",
            "SQL",
            "EDA & Data Visualization",
            "Supervised Learing",
            "Deep Learning & AI",
            "Gen AI",
        ],
    },
    {
        id: 6,
        courseid:"c6",
        image: img16,
        status:"Recommended",
        modules: "9 Modules",
        duration: "8 Months",
        title: "Java Spring boot",
        coursename:"Java Spring Full Stack Development",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "It is expected that Java Spring Technology will grow immensely in the coming years. If you are in search of a career that can help you involve yourself in something that is global, then Java Spring training can help you achieve that . More and more businesses are now understanding that business intelligence is very much impacted by machine learning and are opting to invest in it ",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "OOPS",
            "Advanced JAVA",
            "Java Database Programming",
            "JDK new Featured",
            "JAVA Enterprise Edition",
            "Spring & Spring Boot",
        ],
    },
    {
        id: 7,
        courseid:"c7",
        image: img17,
        status:"Recommended",
        modules: "9 Modules",
        duration: "7 Months",
        title: "Asp.net MVC",
        coursename:"Asp.net MVC with Angular - Full Stack",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"20",
        languagAndTools:"17+",
        courseDescription: "If you are planning to build a career in the IT industry, you would have heard about ASP.Net. It is a powerful programming language used by many computer programmers. With so many computer programming languages out there, it is quite natural for you to wonder if attending ASP.Net training can help you successfully launch your IT career. ",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "C# Programming",
            "ASP.Net",
            "ASP.Net Windows Forms",
            "Advanced Programming With ASP.NET",
            "ASP .Net Core",
            "Angular",
        ],
    },
    {
        id: 8,
        courseid:"c8",
        image: img18,
        status:"Most placed",
        modules: "9 Modules",
        duration: "8 Months",
        title: "Python Data Analytics",
        coursename:"Python Data Analytics with Power BI",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "Our comprehensive Python Data Analytics with Power BI program equips you with in-demand skills through hands-on training. From Python fundamentals and SQL to advanced data analysis techniques and Power BI dashboarding, our 4-month curriculum is designed by industry experts to fast-track your career in data analytics.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "SQL",
            "Exploratory Data Analytics",
            "Power BI",
        ],
    },
    {
        id: 9,
        courseid:"c9",
        image: img19,
        status:"Recommended",
        modules: "9 Modules",
        duration: "6 Months",
        title: "Flutter",
        coursename:"Best Flutter Training In Kochi (Cochin) & Calicut (Kozhikode)",
        rating:"4.98",
        subtitle: "100% Placement assistance",
        sessionduration:"2Hours/ Day",
        scheduleddays: "Monday to Friday",
        mode:"Offline/Online",
        Enrolled:"12",
        languagAndTools:"15+",
        courseDescription: "The MEAN / MERN Stack training helps you to get complete knowledge in all JavaScript Technologies and make you a skilled MEAN Stack developer. We have real-time working professionals as trainers who can train and master you in both front-end and back-end development and build your career.",
        contentTitle:"Web Components",
        contentDescription:"HTML, CSS, GIT, JavaScript / ES6, TypeScript, Bootstrap.",
        topics: [
            "MongoDb",
            "Express js",
            "Angular",
            "react js",
            "Node.js",
            "Next.js",
        ],
    },
]